### ISSUE TITLE
TypeError: Cannot read property 'confirm' of undefined

### ISSUE THREAD

**Issue by paul-watkins-croud** [CroudSupport/croud-layout#26]
This appears on all SPAs utilising Croud Layout

![image](https://user-images.githubusercontent.com/14161025/38039397-13eeec40-32a5-11e8-883e-3e4be74b5daa.png)

**Comment by BrockReece** [comment]
Looks like the croud-confirm component may not be loading in time in the App.vue
I'll look into it.
